name: Package

on:
  release:
    types: [created]

jobs:
  publish:
    uses: brewen-dev/workflows/publish.yml@master
    with:
      release_tag: ${{ github.event.release.tag_name }}
    secrets: inherit
