name: Package

on:
  release:
    types: [created]
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Set git user
        run: |
          git config --global user.name "CI"
          git config --global user.email "deploy@brewen.dev"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile
      - run: echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH

      - name: Bump version
        run: source ${{ github.workspace }}/scripts/bump.sh

      - name: Build
        run: . ${{ github.workspace }}/scripts/build.sh
      - run: cd ${{ github.workspace }}/dist

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit, tag and push
        run: |
          git add .
          git commit -m "chore: release $PKG_VERSION"
          git tag $PKG_VERSION
          git push origin ${{ github.ref }} --follow-tags
