name: Package

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Add node_modules/.bin to PATH
        run: echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH

      - name: Check if artifact exists
        uses: brewcoua/artifact-exists@v1.0.0
        with:
          name: style-${{ github.event.release.tag_name }}.tar.gz

      - name: Download release artifact
        if: env.ARTIFACT_EXISTS == 'true'
        uses: actions/download-artifact@v2
        with:
          name: style-${{ github.event.release.tag_name }}.tar.gz
      - name: Unpack release artifact
        if: env.ARTIFACT_EXISTS == 'true'
        run: |
          tar -xzf style-${{ github.event.release.tag_name }}.tar.gz -C dist
          rm style-${{ github.event.release.tag_name }}.tar.gz
          cd dist

      - name: Build
        if: env.ARTIFACT_EXISTS != 'true'
        run: |
          bun run build
          cd dist

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

