name: Tag

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Add node_modules/.bin to PATH
        run: echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH

      - name: Setup git user
        run: |
          git config --global user.name "Brewen.DEV/CI"
          git config --global user.email "deploy@brewen.dev"

      - name: Release tag
        id: release
        run: |
          bun run release
          echo "changed=$(git log origin/master..master --oneline | wc -l)" >> $GITHUB_OUTPUT
          echo "PKG_VERSION=v$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Push
        if: steps.release.outputs.changed != '0'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Build
        if: steps.release.outputs.changed != '0'
        run: |
          bun run build
          cd dist

      - name: Pack artifact
        if: steps.release.outputs.changed != '0'
        run: |
          tar -czf style-$PKG_VERSION.tar.gz * && mv style-$PKG_VERSION.tar.gz ../
          cd ..
        env:
          PKG_VERSION: ${{ env.PKG_VERSION }}

      - name: Create release
        if: steps.release.outputs.changed != '0'
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "style-${{ env.PKG_VERSION }}.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.PKG_VERSION }}
          tag: ${{ env.PKG_VERSION }}
          bodyFile: "CHANGELOG.md"
